import './globals.css'
import { Roboto } from 'next/font/google'
import { Providers } from '../../providers'

const font = Roboto({ subsets: ['latin'], weight: ['300'] })

export const metadata = {
  title: 'Prometheus R&D Tijuana: Soluciones Digitales',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
